import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
// import TopHeader from "@/components/top-header";
import { ThemeToggle } from "@/components/theme-toggle";

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider>
        <SidebarProvider>
          <div className="flex h-screen w-screen">
            <Sidebar />
            <main className="flex-1">
              {children}
            </main>
          </div>
        </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
